name: Module-Install-InstallDirs
version: 0.01
abstract: Module::Install extension to detect INSTALLDIR settings
author: Graham Barr <gbarr@pobox.com>
license: perl
distribution_type: module
private:
  directory:
    - inc
generated_by: Module::Install version 0.24
